//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFORM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMIN_DEPARTMENT()
        {
            this.EFORM_QM_GEOMETRICS_DETAILS = new HashSet<EFORM_QM_GEOMETRICS_DETAILS>();
            this.EFORM_PIU_GENERAL_INFO = new HashSet<EFORM_PIU_GENERAL_INFO>();
            this.EFORM_PIU_MIX_DESIGN_DETAILS = new HashSet<EFORM_PIU_MIX_DESIGN_DETAILS>();
            this.EFORM_PIU_PREVIOUS_INSP_DETAILS = new HashSet<EFORM_PIU_PREVIOUS_INSP_DETAILS>();
            this.EFORM_PIU_PRGS_DETAILS = new HashSet<EFORM_PIU_PRGS_DETAILS>();
            this.EFORM_PIU_QC__DETAILS = new HashSet<EFORM_PIU_QC__DETAILS>();
            this.EFORM_QM_ARRANGEMENTS_OBS_DETAILS = new HashSet<EFORM_QM_ARRANGEMENTS_OBS_DETAILS>();
            this.EFORM_QM_PRESENT_WORK_DETAILS = new HashSet<EFORM_QM_PRESENT_WORK_DETAILS>();
            this.UM_User_Master1 = new HashSet<UM_User_Master>();
        }
    
        public int ADMIN_ND_CODE { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public int MAST_AGENCY_CODE { get; set; }
        public Nullable<int> MAST_PARENT_ND_CODE { get; set; }
        public string MAST_ND_TYPE { get; set; }
        public string ADMIN_ND_NAME { get; set; }
        public string ADMIN_ND_ADDRESS1 { get; set; }
        public string ADMIN_ND_ADDRESS2 { get; set; }
        public Nullable<int> MAST_DISTRICT_CODE { get; set; }
        public string ADMIN_ND_PIN { get; set; }
        public string ADMIN_ND_STD1 { get; set; }
        public string ADMIN_ND_STD2 { get; set; }
        public string ADMIN_ND_PHONE1 { get; set; }
        public string ADMIN_ND_PHONE2 { get; set; }
        public string ADMIN_ND_STD_FAX { get; set; }
        public string ADMIN_ND_FAX { get; set; }
        public string ADMIN_ND_MOBILE_NO { get; set; }
        public string ADMIN_ND_EMAIL { get; set; }
        public string ADMIN_ND_REMARKS { get; set; }
        public Nullable<System.DateTime> ADMIN_SBD_DATE { get; set; }
        public string ADMIN_PDF_KEY { get; set; }
        public string ADMIN_EMAIL_CC { get; set; }
        public string ADMIN_ND_TAN_NO { get; set; }
        public string ADMIN_BANK_AUTH_ENABLED { get; set; }
        public Nullable<System.DateTime> ADMIN_BA_ENABLE_DATE { get; set; }
        public string ADMIN_EPAY_MAIL { get; set; }
        public Nullable<System.DateTime> ADMIN_EPAY_ENABLE_DATE { get; set; }
        public string ADMIN_EREMITTANCE_ENABLED { get; set; }
        public Nullable<System.DateTime> ADMIN_EREMIT_ENABLED_DATE { get; set; }
        public Nullable<int> ADMIN_EPAY_DPIU_CODE { get; set; }
        public string ADMIN_ND_ACTIVE { get; set; }
        public Nullable<System.DateTime> ADMIN_ND_CLOSE_DATE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_GEOMETRICS_DETAILS> EFORM_QM_GEOMETRICS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_GENERAL_INFO> EFORM_PIU_GENERAL_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_MIX_DESIGN_DETAILS> EFORM_PIU_MIX_DESIGN_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_PREVIOUS_INSP_DETAILS> EFORM_PIU_PREVIOUS_INSP_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_PRGS_DETAILS> EFORM_PIU_PRGS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_PIU_QC__DETAILS> EFORM_PIU_QC__DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_ARRANGEMENTS_OBS_DETAILS> EFORM_QM_ARRANGEMENTS_OBS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFORM_QM_PRESENT_WORK_DETAILS> EFORM_QM_PRESENT_WORK_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_User_Master> UM_User_Master1 { get; set; }
        public virtual MASTER_AGENCY MASTER_AGENCY { get; set; }
    }
}
