//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFORM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EformEntities : DbContext
    {
        public EformEntities()
            : base("name=EformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_DEPARTMENT> ADMIN_DEPARTMENT { get; set; }
        public virtual DbSet<EFORM_MASTER> EFORM_MASTER { get; set; }
        public virtual DbSet<EFORM_MASTER_WORK_ITEM> EFORM_MASTER_WORK_ITEM { get; set; }
        public virtual DbSet<EFORM_PIU_GENERAL_INFO> EFORM_PIU_GENERAL_INFO { get; set; }
        public virtual DbSet<EFORM_PIU_MIX_DESIGN_DETAILS> EFORM_PIU_MIX_DESIGN_DETAILS { get; set; }
        public virtual DbSet<EFORM_PIU_PREVIOUS_INSP_DETAILS> EFORM_PIU_PREVIOUS_INSP_DETAILS { get; set; }
        public virtual DbSet<EFORM_PIU_PRGS_DETAILS> EFORM_PIU_PRGS_DETAILS { get; set; }
        public virtual DbSet<EFORM_PIU_QC__DETAILS> EFORM_PIU_QC__DETAILS { get; set; }
        public virtual DbSet<EFORM_QC_OFFICIAL_DETAILS> EFORM_QC_OFFICIAL_DETAILS { get; set; }
        public virtual DbSet<EFORM_QM_ARRANGEMENTS_OBS_DETAILS> EFORM_QM_ARRANGEMENTS_OBS_DETAILS { get; set; }
        public virtual DbSet<EFORM_QM_GEOMETRICS_DETAILS> EFORM_QM_GEOMETRICS_DETAILS { get; set; }
        public virtual DbSet<EFORM_QM_GEOMETRICS_OBS_DETAILS> EFORM_QM_GEOMETRICS_OBS_DETAILS { get; set; }
        public virtual DbSet<EFORM_QM_PRESENT_WORK_DETAILS> EFORM_QM_PRESENT_WORK_DETAILS { get; set; }
        public virtual DbSet<EFORM_QM_QC_TEST_DETAILS> EFORM_QM_QC_TEST_DETAILS { get; set; }
        public virtual DbSet<EFORM_QM_QUALITY_ATTENTION> EFORM_QM_QUALITY_ATTENTION { get; set; }
        public virtual DbSet<EFORM_QM_TEST_RESULT_VERIFICATION_DETAILS> EFORM_QM_TEST_RESULT_VERIFICATION_DETAILS { get; set; }
        public virtual DbSet<EXEC_LSB_MONTHLY_STATUS> EXEC_LSB_MONTHLY_STATUS { get; set; }
        public virtual DbSet<EXEC_ROADS_MONTHLY_STATUS> EXEC_ROADS_MONTHLY_STATUS { get; set; }
        public virtual DbSet<IMS_SANCTIONED_PROJECTS> IMS_SANCTIONED_PROJECTS { get; set; }
        public virtual DbSet<MASTER_BLOCK> MASTER_BLOCK { get; set; }
        public virtual DbSet<MASTER_DISTRICT> MASTER_DISTRICT { get; set; }
        public virtual DbSet<MASTER_MONTH> MASTER_MONTH { get; set; }
        public virtual DbSet<MASTER_STATE> MASTER_STATE { get; set; }
        public virtual DbSet<UM_Action_Master> UM_Action_Master { get; set; }
        public virtual DbSet<UM_HomePage_Master> UM_HomePage_Master { get; set; }
        public virtual DbSet<UM_Level_Combination> UM_Level_Combination { get; set; }
        public virtual DbSet<UM_Level_Master> UM_Level_Master { get; set; }
        public virtual DbSet<UM_Menu_Master> UM_Menu_Master { get; set; }
        public virtual DbSet<UM_MENU_SCHEME_TYPE_COMBINATION> UM_MENU_SCHEME_TYPE_COMBINATION { get; set; }
        public virtual DbSet<UM_Module_Master> UM_Module_Master { get; set; }
        public virtual DbSet<UM_Role_Action_Mapping> UM_Role_Action_Mapping { get; set; }
        public virtual DbSet<UM_Role_Level_Mapping> UM_Role_Level_Mapping { get; set; }
        public virtual DbSet<UM_Role_Master> UM_Role_Master { get; set; }
        public virtual DbSet<UM_Role_Menu_Mapping> UM_Role_Menu_Mapping { get; set; }
        public virtual DbSet<UM_Rpt_Menu_Master> UM_Rpt_Menu_Master { get; set; }
        public virtual DbSet<UM_Security_Question_Answer> UM_Security_Question_Answer { get; set; }
        public virtual DbSet<UM_Security_Question_Master> UM_Security_Question_Master { get; set; }
        public virtual DbSet<UM_User_Log> UM_User_Log { get; set; }
        public virtual DbSet<UM_User_Master> UM_User_Master { get; set; }
        public virtual DbSet<UM_User_Profile> UM_User_Profile { get; set; }
        public virtual DbSet<UM_User_Role_Mapping> UM_User_Role_Mapping { get; set; }
        public virtual DbSet<CONTRACTOR_REGISTRATION_DETAILS> CONTRACTOR_REGISTRATION_DETAILS { get; set; }
        public virtual DbSet<UM_Citizen_User_Master> UM_Citizen_User_Master { get; set; }
        public virtual DbSet<UM_Css_Master> UM_Css_Master { get; set; }
        public virtual DbSet<UM_Language_Master> UM_Language_Master { get; set; }
        public virtual DbSet<UM_MENU_FUND_TYPE_COMBINATION> UM_MENU_FUND_TYPE_COMBINATION { get; set; }
        public virtual DbSet<MASTER_AGENCY> MASTER_AGENCY { get; set; }
        public virtual DbSet<MASTER_CONTRACTOR> MASTER_CONTRACTOR { get; set; }
        public virtual DbSet<MASTER_YEAR> MASTER_YEAR { get; set; }
        public virtual DbSet<UM_Menu_Master_SHADOW> UM_Menu_Master_SHADOW { get; set; }
        public virtual DbSet<UM_Role_Action_Mapping_SHADOW> UM_Role_Action_Mapping_SHADOW { get; set; }
        public virtual DbSet<UM_Role_Level_Mapping_SHADOW> UM_Role_Level_Mapping_SHADOW { get; set; }
        public virtual DbSet<UM_Role_Menu_Mapping_SHADOW> UM_Role_Menu_Mapping_SHADOW { get; set; }
        public virtual DbSet<UM_USER_MASTER_SHADOW_13Apr2021> UM_USER_MASTER_SHADOW_13Apr2021 { get; set; }
        public virtual DbSet<UM_USER_MASTER_SHADOW> UM_USER_MASTER_SHADOW { get; set; }
    }
}
