//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFORM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_BLOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_BLOCK()
        {
            this.UM_Citizen_User_Master = new HashSet<UM_Citizen_User_Master>();
        }
    
        public int MAST_BLOCK_CODE { get; set; }
        public string MAST_BLOCK_NAME { get; set; }
        public int MAST_DISTRICT_CODE { get; set; }
        public Nullable<int> MAST_BLOCK_ID { get; set; }
        public string MAST_IS_DESERT { get; set; }
        public string MAST_IS_TRIBAL { get; set; }
        public string MAST_PMGSY_INCLUDED { get; set; }
        public string MAST_SCHEDULE5 { get; set; }
        public string MAST_IAP_BLOCK { get; set; }
        public string MAST_BLOCK_ACTIVE { get; set; }
        public int MAST_NIC_STATE_CODE { get; set; }
        public Nullable<int> MAST_NIC_DISTRICT_CODE { get; set; }
        public Nullable<int> MAST_NIC_BLOCK_CODE { get; set; }
        public string MAST_LOCK_STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
        public string MAST_IS_BADB { get; set; }
    
        public virtual MASTER_DISTRICT MASTER_DISTRICT { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_Citizen_User_Master> UM_Citizen_User_Master { get; set; }
    }
}
