//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFORM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_STATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_STATE()
        {
            this.ADMIN_DEPARTMENT = new HashSet<ADMIN_DEPARTMENT>();
            this.MASTER_DISTRICT = new HashSet<MASTER_DISTRICT>();
            this.UM_User_Master1 = new HashSet<UM_User_Master>();
            this.UM_Citizen_User_Master = new HashSet<UM_Citizen_User_Master>();
        }
    
        public int MAST_STATE_CODE { get; set; }
        public string MAST_STATE_NAME { get; set; }
        public string MAST_STATE_UT { get; set; }
        public string MAST_STATE_TYPE { get; set; }
        public string MAST_STATE_SHORT_CODE { get; set; }
        public string MAST_STATE_ACTIVE { get; set; }
        public int MAST_NIC_STATE_CODE { get; set; }
        public string MAST_LOCK_STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMIN_DEPARTMENT> ADMIN_DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_DISTRICT> MASTER_DISTRICT { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_User_Master> UM_User_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_Citizen_User_Master> UM_Citizen_User_Master { get; set; }
    }
}
