//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFORM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_CONTRACTOR
    {
        public int MAST_CON_ID { get; set; }
        public string MAST_CON_SUP_FLAG { get; set; }
        public string MAST_CON_COMPANY_NAME { get; set; }
        public string MAST_CON_FNAME { get; set; }
        public string MAST_CON_MNAME { get; set; }
        public string MAST_CON_LNAME { get; set; }
        public string MAST_CON_ADDR1 { get; set; }
        public string MAST_CON_ADDR2 { get; set; }
        public int MAST_DISTRICT_CODE_ADDR { get; set; }
        public int MAST_STATE_CODE_ADDR { get; set; }
        public string MAST_CON_PIN { get; set; }
        public string MAST_CON_STD1 { get; set; }
        public string MAST_CON_STD2 { get; set; }
        public string MAST_CON_PHONE1 { get; set; }
        public string MAST_CON_PHONE2 { get; set; }
        public string MAST_CON_STD_FAX { get; set; }
        public string MAST_CON_FAX { get; set; }
        public string MAST_CON_MOBILE { get; set; }
        public string MAST_CON_EMAIL { get; set; }
        public string MAST_CON_PAN { get; set; }
        public string MAST_CON_AADHAR { get; set; }
        public string MAST_CON_LEGAL_HEIR_FNAME { get; set; }
        public string MAST_CON_LEGAL_HEIR_MNAME { get; set; }
        public string MAST_CON_LEGAL_HEIR_LNAME { get; set; }
        public Nullable<System.DateTime> MAST_CON_EXPIRY_DATE { get; set; }
        public string MAST_CON_REMARKS { get; set; }
        public string MAST_CON_STATUS { get; set; }
        public string MAST_LOCK_STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
        public string MAST_CON_DC_FILE_NAME { get; set; }
    }
}
