//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFORM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_DISTRICT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_DISTRICT()
        {
            this.MASTER_BLOCK = new HashSet<MASTER_BLOCK>();
            this.UM_Citizen_User_Master = new HashSet<UM_Citizen_User_Master>();
        }
    
        public int MAST_DISTRICT_CODE { get; set; }
        public string MAST_DISTRICT_NAME { get; set; }
        public int MAST_STATE_CODE { get; set; }
        public int MAST_DISTRICT_ID { get; set; }
        public string MAST_PMGSY_INCLUDED { get; set; }
        public string MAST_IAP_DISTRICT { get; set; }
        public string MAST_DISTRICT_ACTIVE { get; set; }
        public int MAST_NIC_STATE_CODE { get; set; }
        public Nullable<int> MAST_NIC_DISTRICT_CODE { get; set; }
        public string MAST_LOCK_STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public string IPADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_BLOCK> MASTER_BLOCK { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
        public virtual UM_User_Master UM_User_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UM_Citizen_User_Master> UM_Citizen_User_Master { get; set; }
    }
}
