//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFORM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UM_Menu_Master_SHADOW
    {
        public long AuditId { get; set; }
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public int ParentID { get; set; }
        public int LevelGroupCode { get; set; }
        public short Sequence { get; set; }
        public short HorizontalSequence { get; set; }
        public short VerticalLevel { get; set; }
        public bool IsActive { get; set; }
        public string MenucombinationCode { get; set; }
        public Nullable<short> FundTypeCombinationCode { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
